services:
#    gm_videotheque.example:
#        class: GM\VideothequeBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

     categorie_handler:
         class: GM\VideothequeBundle\Handler\CategorieHandler
         arguments: []

     film_handler:
         class: GM\VideothequeBundle\Handler\FilmHandler
         arguments: []