<?php

namespace GM\VideothequeBundle\Repository;

use GM\VideothequeBundle\Entity\Film;

/**
 * FilmRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FilmRepository extends \Doctrine\ORM\EntityRepository
{
    
}
