<?php
namespace AppBundle\DataFixtures\ORM;

use Doctrine\Bundle\FixturesBundle\Fixture;
use Doctrine\Common\Persistence\ObjectManager;
use Symfony\Component\DependencyInjection\ContainerAwareInterface;
use GM\VideothequeBundle\Entity\Categorie;
use GM\VideothequeBundle\Entity\Film;
use AppBundle\Entity\User;
use Faker;

class VideothequeFixtures extends Fixture implements ContainerAwareInterface
{
    protected $film_data = [
        "#Eurotrip",
        "100 kg d'étoiles ",
        "A 2 heures de Paris",
        "Affamés (Les)",
        "Ami-ami",
        "Baby Phone",
        "Barman du transatlantique (Le)",
        "Bergère",
        "Bêtes blondes",
        "Bonnes mères",
        "Break it all !",
        "Ce qu'il nous reste de la révolution",
        "Chatouilles (Les)",
        "Christ(off)",
        "Conseil de famille",
        "Danse, l'Afrique danse",
        "Dents, pipi, au lit (Les)",
        "Des bobines et des hommes",
        "Deux fils",
        "Doudou (Le)",
        "Du soleil dans mes yeux",
        "Echappée (L')",
        "En attendant les hirondelles",
        "Fils de Garches",
        "Finale (La) ",
        "Full frontal",
        "Girls with balls",
        "Grande-Synthe",
        "Gueule d'ange",
        "Homme qui penche (L')",
        "Il se passe quelque chose",
        "Intime conviction",
        "Jessica forever",
        "Jeune fille sans mains (La)",
        "Kiss and cry",
        "La surface de réparation",
        "Leïla",
        "Les Municipaux, ces héros",
        "Love Addict",
        "Lumière !",
        "Madame B, histoire d'une nord-coréenne",
        "Maman est morte",
        "Manoir (Le)",
        "Marche ou crève",
        "Maria by Callas",
        "Meltem",
        "Même pas froid",
        "Mes frères",
        "Moissonneurs (Les)",
        "Mon brillantissime divorce",
        "Mon tissu préféré",
        "Mustang",
        "Ordre des médecins (L')",
        "Pearl",
        "Petit proxénète (Le)",
        "Poulain (Le)",
        "Premières vacances",
        "Reptiles (Les)",
        "Revenge",
        "Roulez jeunesse",
        "Sans adieu",
        "Scelsi le premier mouvement de l'immobile",
        "Sofia",
        "Sun",
        "Tout là-haut",
        "Tout le monde debout",
        "Traversée (La)",
        "Une histoire de l'art",
        "Une jeunesse sauvage",
        "Vierges",
        "Vieux fourneaux (Les)",
        "Voyage d'Ailo (Le)",
        "16 levers de soleil",
        "A la rencontre de mon père",
        "A perdre haleine",
        "Ady Gasy",
        "Amour qu'il nous faut (L')",
        "Après la guerre",
        "As de la jungle (Les) - le film",
        "Ascension (L')",
        "Ava",
        "Banc d'attente",
        "Bienvenue au Gondwana",
        "Blockbuster",
        "Bloody Milk",
        "Carnivores (Les)",
        "Chouquette",
        "Clichy kids",
        "Comme des lions",
        "Comme ils respirent",
        "Comment j'ai rencontré mon père",
        "Cornélius, le meunier hurlant",
        "Corporate",
        "Croc Blanc",
        "Dans les pas de Trisha Brown",
        "Dérive d'un été",
        "Diane a les épaules",
        "Divan du monde (Le)",
        "Django Melodies",
        "Drôles de petites bêtes",
        "Exotica, Erotica, Etc.",
        "Femme de mon oncle grec (La)",
        "Fête est finie (La)",
        "Filles de Reims (Les)",
        "Filles du feu",
        "Forêt des Quinconces (La)",
        "Funan",
        "Garçon manqué",
        "Grand froid",
        "Gueule du loup (La)",
        "H4-93",
        "Jeune femme",
        "Jusqu'à la garde",
        "Karim",
        "Kinoa",
        "Ladies",
        "Links of life",
        "Loue moi",
        "Luna",
        "Mariage (blanc) pour tous",
        "Mécanique de l'ombre (La)",
        "Mélodie (La)",
        "Menina",
        "Merci patron !",
        "Monsieur et Madame Adelman",
        "Moutonnière (La)",
        "Paris la blanche",
        "Passade",
        "Patients",
        "Pauline s'arrache",
        "Petit Locataire (Le)",
        "Philosophes (Les)",
        "Pour le réconfort",
        "Prince de Nothingwood (Le)",
        "Rire de ma mère (Le)",
        "Sales gosses",
        "Sel",
        "Semeur (Le)",
        "Si tu voyais son cœur",
        "Sociologue et l'ourson (La)",
        "Soif de vivre (La)",
        "Soleil battant",
        "Sparring",
        "Tazzeka",
        "Tour (La)",
        "Un jour ça ira",
        "Vaurien",
        "Vent du nord",
        "Versets de l'oubli (Les)",
        "Vie de château (La)",
        "Willy 1 er",
        "Zombillenium",
        "A mon âge je me cache encore pour fumer",
        "A quatre mains",
        "Amis publics n°1",
        "Apnée",
        "Athènes, les éclats",
        "Bricks",
        "Cessez-le-feu",
        "Ciel rouge",
        "Cité muette (La)",
        "Compte tes blessures",
        "Correspondant (Le)",
        "Crash test Aglaé",
        "Cruel",
        "Danseuse (La)",
        "De sas en sas",
        "Désemparés (Les)",
        "Dogs",
        "D'une pierre deux coups",
        "En attache",
        "Ennemi invisible (L')",
        "Et les mistrals gagnants…",
        "Femmes en cuisine(s)",
        "Five",
        "Fleur de tonnerre",
        "Folle Histoire de Max et Léon (La)",
        "Gorge cœur ventre",
        "Grand Jeu (Le)",
        "Grave",
        "I paisani",
        "Indomptée (L')",
        "Irréprochable",
        "Jeunesse",
        "Joséphine est enceinte",
        "Jours de France",
        "Ladji nye",
        "Loup-garou",
        "M",
        "M et le 3ème secret",
        "Mauvais œil",
        "Mercenaire",
        "New Territories",
        "Œil du cyclone (L')",
        "Papesse Jeanne (La)",
        "Parole de kamikaze",
        "Règle du jeu (La)",
        "Rosalie Blum",
        "Sahara",
        "Secret des banquises (Le)",
        "Secret d'hiver",
        "Spartacus & Cassandra",
        "The Man who Loved Women",
        "Un jeune poète",
        "Un jour mon prince",
        "Vendeur",
        "Venise sous la neige",
        "Vicky",
        "Vie des gens (La)",
        "Vie pure (La)",
        "Vienne avant la nuit",
        "Voyageur (Le)",
        "West coast",
        "Where is Rocky II ?",
        "Adama",
        "Adama",
        "Amours et métamorphoses",
        "Anna",
        "Arrêtez-moi là",
        "Bang gang",
        "Bêtises (Les)",
        "Canicule",
        "Chaises musicales (Les)",
        "Cow-boys (Les)",
        "Dealer",
        "Deux Amis (Les)",
        "Diamant noir",
        "Dieu protège ma fille",
        "Edmond, un portrait de baudoin",
        "Elan (L')",
        "Eva et Léon",
        "Fille du patron (La)",
        "Flux",
        "Front du Wakhan (Le)",
        "House of time",
        "Hypnodream",
        "Il nous reste la nuit",
        "J'ai dégagé Ben Ali",
        "J'demande pas la lune, juste quelques étoiles",
        "Je suis à vous tout de suite",
        "Je suis un soldat",
        "Ladygrey",
        "Lamb",
        "Ma sacrée jeunesse",
        "Macadam baby",
        "Machin/machine",
        "Monde de Fred (Le)",
        "Moonwalk",
        "Mustang",
        "Nous trois ou rien",
        "Nouveau (Le)",
        "Nouvelles Aventures d'Aladin (Les)",
        "Papa ou maman d'abord ?",
        "Papa was not a Rolling Stone",
        "Par accident",
        "Paris Willoughby",
        "Rencontres",
        "Resistance de l'air (La)",
        "Rois du monde (Les)",
        "Sangre de mi sangre",
        "Si par hasard",
        "Sous les jupes des filles",
        "Steak (r)évolution",
        "Swim little fish swim",
        "Talent de mes amis (Le)",
        "The Red Turtle",
        "Tout en haut du monde",
        "Un vrai faussaire",
        "Une jeunesse allemande",
        "Verdon secret",
        "Voyage en Chine",
        "Voyoucratie",
        "Zouzou",
        "Zugzwang",
        "98",
        "419",
        "A love you",
        "Ablations",
        "Ainsi squattent-ils",
        "Amour sur place ou à emporter",
        "Angélique",
        "Après la bataille",
        "Atlit",
        "Bébé tigre",
        "Bogota",
        "Bonheur (Le)",
        "Bonheur… terre promise (Le)",
        "Caricaturistes - fantassins de la démocratie",
        "Casa nostra",
        "Chromobiles",
        "Combattants (Les)",
        "Coming in",
        "Comment les chèvres de ma mère sont devenues européennes",
        "Delivrez-moi du mal",
        "Des étoiles",
        "Dimanche 4 janvier",
        "Discount",
        "Du sable à la poussière",
        "Elle l'aime, elle l'adore",
        "Esto es lo que hay",
        "Etre",
        "Fidelio, l'odyssée d'Alice",
        "Francis (Les)",
        "Generation Mitterrand",
        "Gouffres (Les)",
        "Grande Séduction (La)",
        "Guy Georges, la traque",
        "Jamais le premier soir",
        "Jamel",
        "Libre, seul et assoupi",
        "Lili Rose",
        "Lou !",
        "Mademoiselle C",
        "Mante religieuse (La)",
        "Max et Lenny",
        "Nuits d'été (Les)",
        "Orage",
        "Papa lumière",
        "Paradise lost",
        "Parenthèse",
        "Passion selon Laetitia (La)",
        "Patria obscura",
        "Porte d'Anna (La)",
        "Pouvoir (Le)",
        "Qu'Allah bénisse la France",
        "Qui vive",
        "Rengaine",
        "Rue des cités",
        "Run",
        "Sarajeviens",
        "Situation amoureuse : c'est compliqué",
        "Sud eau nord déplacer",
        "Tempête sous un crane",
        "Terre battue",
        "Tonnerre",
        "Tristesse club",
        "Un monde truqué",
        "Venise sous la neige",
        "Victor Young Perez",
        "Vincent",
        "You'll never walk alone",
        "Zona franca",
        "A COUP SÛR",
        "ADULESCENT (L')",
        "ARMEE DU SALUT (L')",
        "ASTERIX ET LE DOMAINE DES DIEUX",
        "AUTRE VIE DE RICHARD KEMP (L')",
        "BANGKOK RENAISSANCE",
        "BATAILLE DE SOLFERINO (LA)",
        "BEAUTE, L'ART RESCAPE DES CAMPS NAZIS (LA)",
        "BELLE VIE (LA)",
        "BELLES ANNEES (LES)",
        "BLEU PETROLE",
        "BOVINES OU LA VRAIE VIE DES VACHES",
        "BRACONNE (LA)",
        "BRADDOCK AMERICA",
        "CAGE DOREE (LA)",
        "CHASSE AU SNARK (LA)",
        "CHEBA",
        "CHERCHER LE GARCON",
        "DISPARAISSEZ LES OUVRIERS !",
        "DOUTES",
        "DUNE (LA)",
        "DZMA",
        "EL PUESTO",
        "EN SOLITAIRE",
        "ENTRE LES BRAS, LA CUISINE EN HERITAGE",
        "FLEURS DU MAL",
        "GAMINS (LES)",
        "GARÇONS ET GUILLAUME, A TABLE ! (LES)",
        "GIRAFFADA",
        "GRAND DEPART (LE)",
        "HOTEL DU PARADIS",
        "HYPOTHESE DU MOKELE-MBEMBE (L')",
        "INITIATION",
        "JASMINE",
        "JC COMME JESUS CHRIST",
        "JE M'APPELLE HMMM…",
        "JE SUIS SUPPORTER DU STANDARD",
        "JOUR ATTENDRA (LE)",
        "JULIETTE",
        "LANDES",
        "LOVE LOVE LOVE",
        "MA MAMAN EST EN AMERIQUE, ELLE A RENCONTRE BUFFALO BILL",
        "MARUSSIA",
        "MEME PAS MAL",
        "MINUSCULE",
        "MOHAMED DUBOIS",
        "MOSKOVITCH, MON AMOUR",
        "NANA",
        "NE QUELQUE PART",
        "NOS HEROS SONT MORTS CE SOIR",
        "NOTRE MONDE",
        "OCEANE",
        "OUTREAU, L'AUTRE VERITE",
        "PARIS A TOUT PRIX",
        "PASSER L'HIVER",
        "PETITS PRINCES (LES)",
        "PHOTO",
        "PIECE MANQUANTE (LA)",
        "PIFANO, LES FAUBOURGS DE L'OMBRE",
        "POP REDEMPTION",
        "POURQUOI J'AI (PAS) MANGE MON PERE",
        "QU'ILS REPOSENT EN REVOLTE (DES FIGURES DE GUERRE I)",
        "REINES DU RING (LES)",
        "RENCONTRES D'APRES MINUIT (LES)",
        "RIVES",
        "ROUTE DU RETOUR (LA)",
        "SABABOU, L'ESPOIR",
        "SECRET DE LOULOU (LE)",
        "SENS DE L'AGE (LE)",
        "SENS DE L'HUMOUR (LE)",
        "STRATEGIE DE LA POUSSETTE (LA)",
        "SUPER TRASH",
        "UN P'TIT GARS DE MENILMONTANT",
        "UNE CHANSON POUR MA MERE",
        "UNE HISTOIRE D'AMOUR",
        "VANDAL",
        "VOYAGE EN GUEDIGUIAN",
        "10 JOURS EN OR",
        "AFTER",
        "AIR DE RIEN (L')",
        "ALYAH",
        "AMAZONIA",
        "AMITIÉS SINCÈRES",
        "AMOUR DURE TROIS ANS (L')",
        "ARCHIPELITUDE",
        "ARRÊTE DE PLEURER PÉNÉLOPE",
        "AU GALOP",
        "AUGUSTINE",
        "CASSOS",
        "CERISE SUR LE GÂTEAU (LA)",
        "CETTE ANNÉE-LÀ",
        "CHRONIQUES D'UNE COUR DE RÉCRÉ",
        "CITÉ ROSE (LA)",
        "COMME DES FRERES",
        "CRAWL",
        "DAVID ET MADAME HANSEN",
        "DE FORCE",
        "DELICATESSE (LA)",
        "DES MORCEAUX DE MOI",
        "DÉTROIT MES FANTÔMES",
        "ESPRIT DU VIN \"REVEIL DES TERROIRS\" (L')",
        "ETRE LÀ",
        "EYES FIND EYES",
        "FILLE DU 14 JUILLET (LA)",
        "FILS DU MARCHAND D'OLIVES (LE)",
        "FRIENDS FROM FRANCE",
        "GIGOLA",
        "HÉRITAGE",
        "HONK",
        "ICH NOU (NOS ENFANTS)",
        "ICI ON NOIE LES ALGERIENS 17 OCTOBRE 1961",
        "INCIDENT AT SANS ASYLUM",
        "J'AIME REGARDER LES FILLES",
        "JE ME SUIS FAIT TOUT PETIT",
        "JEUX DES NUAGES ET DE LA PLUIE (LES)",
        "KAIRA (LES)",
        "LENDEMAINS (LES)",
        "MAFROUZA",
        "MAITRE DU MONDE",
        "MARIAGE A MENDOZA",
        "MARIAGE BOULETTE",
        "MAUVAISE FILLE",
        "MOUTON",
        "NESMA",
        "NOS PLUS BELLES VACANCES",
        "NUIT NOMADE (LA)",
        "ON NE CHOISIT PAS SA FAMILLE",
        "OUF",
        "PARADIS DES BETES (LE)",
        "PARIS-MANHATTAN",
        "PAYS RÊVÉ",
        "PLAN DE TABLE",
        "POPULAIRE",
        "POUR QUELQUES POUSSIÈRES",
        "POURQUOI TU PLEURES ?",
        "PRESIDENT (LE)",
        "PSEUDONYM",
        "RADIOSTARS",
        "REUSSIR SA VIE",
        "RIZIÈRE (LA)",
        "SEA, NO SEX AND SUN",
        "SHANGHAÏ-BELLEVILLE",
        "TERRE DES OURS",
        "THE HUNTERS",
        "TRIBULATIONS D'UNE CAISSIERE (LES)",
        "UN MÉDIANOCHE",
        "UNE ESTONIENNE A PARIS",
        "VIE D'UNE AUTRE (LA)",
        "VIE MURMUREE (LA)",
        "ZANA",
        "16 DE BASSE-POINTE (LES)",
        "A CÔTÉ",
        "A L'INTÉRIEUR",
        "AMES ERRANTES (LES)",
        "BOXES",
        "CANDIDAT (LE)",
        "CARAMEL",
        "CE QUE MES YEUX ONT VU",
        "CEUX QUI RESTENT",
        "CHASSEURS DE DRAGONS",
        "CHRYSALIS",
        "CONTRE-ENQUÊTE",
        "DANS LES CORDES",
        "DÉTROMPEZ VOUS",
        "DONNE-MOI LA MAIN",
        "ET TOI T'ES SUR QUI ?",
        "FRONTIÈRE(S)",
        "HÉROS",
        "HOMME QUI MARCHE (L')",
        "JE DÉTESTE LES ENFANTS DES AUTRES",
        "LIENS (LES)",
        "LISA ET LE PILOTE D'AVION",
        "MA PLACE AU SOLEIL",
        "MA VIE N'EST PAS UNE COMEDIE ROMANTIQUE",
        "MANGE, CECI EST MON CORPS",
        "MAUVAISE FOI",
        "MON COLONEL",
        "NAISSANCE DES PIEUVRES",
        "NO POPCORN ON THE FLOOR",
        "NORD-PARADIS",
        "NOS RETROUVAILLES",
        "NUAGE",
        "ODETTE TOULEMONDE",
        "ON NE DEVRAIT PAS EXISTER",
        "OÙ AVAIS-JE LA TÊTE ?",
        "PARDONNEZ-MOI",
        "PAYS A L'ENVERS (LE)",
        "PETIT PEINTRE DU RAJASTHAN (LE)",
        "PEUR(S) DU NOIR",
        "POLTERGAY",
        "REGARDE MOI",
        "REQUIEM POUR BILLY THE KID",
        "SANS MOI",
        "SÉQUENCES MONGOLES",
        "TEL PERE TELLE FILLE",
        "TÊTE DE MAMAN (LA)",
        "TOUS À L'OUEST",
        "TOUT EST PARDONNÉ",
        "UN BEAU MATIN",
        "UN ROMAN POLICIER",
        "UNE ÉPOPÉE",
        "VENT MAUVAIS",
        "VIE D'ARTISTE (LA)",
        "VIE EST UNE GOUTTE SUSPENDUE (LA)",
        "YEUX BANDÉS (LES)",
        "YVETTE, BON DIEU !",
        "A CE SOIR",
        "ALIVE",
        "ALL NIGHT BODEGA",
        "APRES-MIDI DE MONSIEUR ANDESMAS (L')",
        "ATOMIK CIRCUS",
        "AU SECOURS, J'AI 30 ANS",
        "AVANT L'OUBLI",
        "BAIGNEUSES (LES)",
        "BELZEC",
        "BENARES",
        "BIENVENUE EN SUISSE",
        "BRODEUSES",
        "CADEAU D'ELENA (LE)",
        "CARLITOS 13 MEDELLIN",
        "CASABLANCA DRIVER",
        "CAUCHEMAR DE DARWIN (LE)",
        "CHORISTES (LES)",
        "CLARA ET MOI",
        "CLEFS DE LA BAGNOLE (LES)",
        "COMME SI DE RIEN N'ÉTAIT",
        "COU DE LA GIRAFE (LE)",
        "DANS LES CHAMPS DE BATAILLE",
        "DE GUERRE LASSES",
        "DEADLINES",
        "DECRYPTAGE",
        "DERNIER TRAPPEUR (LE)",
        "DES ENFANTS QUI S'AIMENT",
        "ECLAIREUR (L')",
        "ENNEMI NATUREL (L')",
        "ET SI JE PARLE ?",
        "FAIS-MOI REVER",
        "FRERES",
        "GARDIEN DE BUFFLES",
        "GRAND VOYAGE (LE)",
        "ILLUMINATION",
        "INCRUSTE (L') - FALLAIT PAS LE LAISSER ENTRER!",
        "INNOCENCE",
        "J'ME SENS PAS BELLE",
        "LILA DIT CA",
        "MADAME EDOUARD",
        "MALABAR PRINCESS",
        "MASSAI LES GUERRIERS DE LA PLUIE",
        "MATRUBHOOMI UN MONDE SANS FEMMES",
        "MENSONGES ET TRAHISONS ET PLUS SI AFFINITES…",
        "MICHEL STROGOFF",
        "MUR",
        "NARCO",
        "NEG MARON",
        "NOCE D'ÉTÉ",
        "NUIT DE LA VERITE (LA)",
        "ODESSA… ODESSA !",
        "PICCOLO, SAXO ET COMPAGNIE",
        "PODIUM",
        "POLISSONS ET GALIPETTES",
        "PREMIERE FOIS QUE J'AI EU 20 ANS (LA)",
        "QUAND LA MER MONTE",
        "REVENANTS (LES)",
        "ROLE DE SA VIE (LE)",
        "ROMANCES DE TERRE ET D' EAU",
        "SAINT ANGE",
        "STEP BY STEP",
        "SUPERNOVA (EXPERIENCE # 1)",
        "TENJA",
        "TERRE ET CENDRES",
        "TOUJOURS TOUT DROIT",
        "TOUT LE PLAISIR EST POUR MOI",
        "UNE VIE A T'ATTENDRE",
        "YO, SOR ALICE",
        "Polaire",
        "Porier Sauvage (Le)",
        "Poulain (Le)",
        "Première année",
        "Première leçon",
        "Premières vacances",
        "Prière (La)",
        "Problemos (ex  La Communauté)",
        "Promesse de l'aube (La)",
        "Proverbe (Le)",
        "Quien te cantara",
        "Rainbow",
        "Raoul Taburin",
        "Rémi sans famille",
        "Remise de peine",
        "Reptiles (Les)",
        "Retour du héros (Le)",
        "Revanche d'Icare (La)",
        "Revenge",
        "Richard va en enfer",
        "Ricordi ?",
        "Roulez jeunesse",
        "Sage femme",
        "Sans adieu",
        "Santa et Cie",
        "Scandinavian silence",
        "Scelsi le premier mouvement de l'immobile",
        "Si j'étais un homme",
        "Sibel",
        "Sicilian ghost story",
        "Simon et Théodore",
        "Slam",
        "Sofia",
        "Sophia Antipolis",
        "Souffle bleu",
        "Stasis",
        "Submergence",
        "Sujet libre",
        "Sun",
        "Sunset",
        "Synonymes",
        "Taxi 5",
        "Tel Aviv on fire",
        "The captain",
        "The devil outside",
        "The Dishwasher",
        "The load",
        "The man who killed Don Quixote",
        "The mercy of the jungle",
        "Todos lo saben",
        "Tout là-haut",
        "Tout le monde debout",
        "Tout l'or du monde",
        "Train de vies",
        "Transit",
        "Traversée (La)",
        "Tremblements",
        "Tristes Monroes",
        "Trois jours à Quiberon",
        "Tuche 3 (Les) ",
        "Un amour impossible",
        "Un autre monde",
        "Un beau soleil intérieur (ex Des lunettes noires)",
        "Un couteau dans le cœur",
        "Un dans l'autre (L')",
        "Un homme pressé",
        "Un merveilleux couple",
        "Un peuple et son roi",
        "Un profil pour deux (ex #Flora 63)",
        "Une histoire de l'art",
        "Une jeunesse sauvage",
        "Une part d'ombre",
        "Usine (L')",
        "Vent tourne (Le)",
        "Vert désert",
        "Vie mode d'emploi (La)",
        "Vierges",
        "Vieux fourneaux (Les)",
        "Vigile",
        "Volontaire",
        "Voyage d'Ailo (Le)",
        "Voyez comme on danse",
        "Wajib",
        "Yemma",
        "13 M²",
        "35 RHUMS",
        "36 VUES DU PIC ST-LOUP",
        "57000 KM ENTRE NOUS",
        "7 JOURS (LES)",
        "7 MINUTES AU PARADIS",
        "8 FOIS DEBOUT",
        "9 MM",
        "A L'ORIGINE",
        "ADIEU GARY",
        "AFFAIRE FAREWELL (L')",
        "ALGERIE, HISTOIRES A NE PAS DIRE",
        "ALLEZ, RACONTE !",
        "AMER",
        "APPEL DES ARENES (L')",
        "ARBRE ET LA FORÊT (L')",
        "ARMÉE DU CRIME (L')",
        "ARRIVANTS (LES)",
        "ARTHUR 3 ET LA GUERRE DES DEUX MONDES",
        "ARTHUR ET LA VENGEANCE DE MALTAZARD",
        "AU DIABLE STALINE, VIVE LES MARIES !",
        "AU NOM DES TROIS COULEURS",
        "AU VOLEUR",
        "AVANT-POSTE",
        "BABY BLUES",
        "BALTRINGUE (LE)",
        "BANLIEUE 13 - ULTIMATUM",
        "BARONS (LES)",
        "BAS-FONDS",
        "BEAUTIFUL VALLEY",
        "BEAUX GOSSES (LES)",
        "BEL AGE (LE)",
        "BELLAMY",
        "BENA",
        "BESA",
        "BLONDE AUX SEINS NUS (LA)",
        "BOITE DE PANDORE (LA)",
        "BONHEUR DE PIERRE (LE)",
        "BONOBOS",
        "BOUQUET FINAL",
        "BRUIT DES GENS AUTOUR (LE )",
        "CARGO",
        "CARRE BLANC",
        "CELLE QUE J'AIME",
        "CENDRES ET SANG",
        "C'EST DUR D'ETRE AIME PAR DES CONS",
        "C'EST ICI QUE JE VIS",
        "CHANTEUSE DE TANGO (LA)",
        "CHAQUE JOUR EST UNE FÊTE",
        "CHEMIN NOIR (LE)",
        "CHÉRI",
        "CHORON DERNIERE VIE ET MORT DU PROFESSEUR",
        "CINEMAN",
        "COACH (LE)",
        "COCO",
        "COCO CHANEL & IGOR STRAVINSKY",
        "CODE A CHANGÉ (LE)",
        "COLUCHE, L'HISTOIRE D'UN MEC",
        "COMME LES AUTRES",
        "COMPLICES",
        "COMTESSE (LA)",
        "CONCERT (LE)",
        "CRIME EST NOTRE AFFAIRE (LE)",
        "CYPRIEN",
        "DAME DE TRÈFLE (LA)",
        "DANS TON SOMMEIL",
        "DAU",
        "DE L'AUTRE COTE DU LIT",
        "DEMAIN DES L'AUBE",
        "DERNIER POUR LA ROUTE (LE)",
        "DIAMANT 13",
        "DIFFÉRENCE C'EST QUE C'EST PAS PAREIL (LA)",
        "DIX MILLIONS DE CENTIMES",
        "DOMAINE",
        "DOMINATION MASCULINE (LA)",
        "EDEN À L'OUEST",
        "ELÈVE LIBRE",
        "EMMERDEUR (L')",
        "EN SOUVENIR DE NOUS",
        "ENFANCE DU MAL (L')",
        "ENFANTS DE DON QUICHOTTE (ACTE 1) (LES)",
        "ENFER DE HENRI-GEORGES CLOUZOT (L')",
        "ENTER THE VOID (SOUDAIN LE VIDE)",
        "ENVOYES TRES SPECIAUX",
        "ERREUR DE LA BANQUE EN VOTRE FAVEUR",
        "ESPION(S)",
        "EX",
        "EYES OF WAR",
        "FAIS-MOI PLAISIR !",
        "FEMME INVISIBLE (LA)",
        "FIL (LE)",
        "FILLE DU RER (LA)",
        "FIX ME",
        "FLEUR DU DESERT",
        "FOLLE HISTOIRE D'AMOUR DE SIMON ESKENAZY (LA)",
        "FROM PARIS WITH LOVE",
        "GAMINES",
        "GENERATION ELECTRO",
        "GERBOISE BLEUE",
        "GUERRE DES MISS (LA )",
        "HABANA MUDA",
        "HADEWIJCH",
        "HERBES FOLLES (LES)",
        "HERISSON (LE)",
        "HOME SWEET HOME",
        "HOMME DE CHEVET (L')",
        "HOMMES (LES)",
        "HORDE (LA)",
        "HUMAINS",
        "ICH BIN EINE TERRORISTIN",
        "IGOR",
        "IL DIVO",
        "INCOGNITO",
        "INFILTRÉ (L')",
        "IRENE",
        "IVUL",
        "J'AI OUBLIÉ DE TE DIRE",
        "J'AIMERAIS PARTAGER LE PRINTEMPS AVEC QUELQU'UN",
        "JASPER, PINGOUIN EXPLORATEUR",
        "JCVD",
        "JE L'AIMAIS",
        "JE NE DIS PAS NON",
        "JE SUIS",
        "JE SUIS HEUREUX QUE MA MÈRE SOIT VIVANTE",
        "JE VAIS TE MANQUER",
        "J'IRAI DORMIR A HOLLYWOOD",
        "JOHN RABE LE JUSTE DE NANKIN",
        "JOUEUSE",
        "JOUR OU DIEU EST PARTI EN VOYAGE (LE)",
        "KERITY, LA MAISON DES CONTES",
        "KING GUILLAUME",
        "KIROT",
        "KURDISH LOVER",
        "LA CAMARA OSCURA",
        "LAGERFELD CONFIDENTIEL",
        "LARGO WINCH",
        "LASCARS (LES)",
        "LIBERTÉ",
        "LIGNE BLANCHE (LA)",
        "LIGNES DE FRONT",
        "LINO",
        "LOL (LAUGHING OUT LOUD)",
        "LOOKING FOR ERIC",
        "LOUP",
        "LOURDES",
        "LUCKY LUKE",
        "MADEMOISELLE CHAMBON",
        "MAGIQUE",
        "MAGMA",
        "MAISON DE MON PÈRE (LA)",
        "MANIQUERVILLE, LE TEMPS RETROUVÉ",
        "MARCHING BAND",
        "MARGA",
        "MARIAGE CHEZ LES BODIN'S",
        "MER NOIRE",
        "MICMACS À TIRE-LARIGOT",
        "MISSIONNAIRE (LE)",
        "MOI, LA FINANCE ET LE DEVELOPPEMENT DURABLE",
        "MORCEAUX DE CONVERSATIONS AVEC JEAN-LUC GODARD",
        "MOVEON.ORG",
        "NE ME LIBÉREZ PAS JE M'EN CHARGE",
        "NES EN 68",
        "NEUILLY SA MERE !",
        "NO PASARAN IL ÉTAIT UNE FOIS DANS LE SUD-OUEST",
        "NON, MA FILLE, TU N'IRAS PAS DANSER",
        "NUIT BLEUE",
        "NUIT DE CHIEN",
        "NULLE PART TERRE PROMISE",
        "OCÉANS",
        "OPÉRA AU BOUT DU MONDE (L')",
        "ORPAILLEUR",
        "OSS 117 RIO NE RÉPOND PLUS",
        "PARIS NORD SUD",
        "PARTIR",
        "PÈRE DE MES ENFANTS (LE)",
        "PETIT NICOLAS (LE)",
        "PLEIN SUD",
        "POUR UN FILS",
        "POURSUITE",
        "PREMIER CERCLE (LE)",
        "PREMIÈRE ÉTOILE (LA)",
        "PREMIERES NEIGES",
        "QUELQUE CHOSE A TE DIRE",
        "QU'UN SEUL TIENNE ET LES AUTRES SUIVRONT…",
        "R.T.T.",
        "RAPT !",
        "REGATE (LA)",
        "REGRETS (LES)",
        "RICKY",
        "RIEN À PERDRE",
        "RIO SEX COMEDY",
        "ROBE DU SOIR (LA)",
        "ROI DE L'ÉVASION (LE)",
        "ROMAINE PAR MOINS 30",
        "RONDO",
        "ROSE ET NOIR",
        "RUBAN BLANC (LE)",
        "SAFARI",
        "SAGAN",
        "SAINTE VICTOIRE (LA)",
        "SANS RANCUNE !",
        "SEL DE LA MER (LE)",
        "SEMINAIRE (LE)",
        "SICILIENNE (LA)",
        "SIMON KONIANSKI",
        "SŒUR SOURIRE",
        "SOLOMON KANE",
        "SOMMEIL BLANC",
        "TABARLY",
        "TELLEMENT PROCHES",
        "TEMPS DE LA KERMESSE EST TERMINÉ (LE)",
        "TEMPS DES GRACES (LE)",
        "TEMPS D'UN REGARD (LE)",
        "TEMPS QU'IL RESTE (LE )",
        "TERRE DE LA FOLIE (LA)",
        "THE DUCHESS",
        "THE GOOD HEART",
        "THE PRODIGIES",
        "TRANSPORTEUR 3 (LE)",
        "TRES TRES GRANDE ENTREPRISE (LA)",
        "TRICHEUSE",
        "ULTIMATUM",
        "UN CHAT, UN CHAT",
        "UN HOMME ET SON CHIEN",
        "UN PROPHÈTE",
        "UNE AFFAIRE D'ETAT",
        "UNE SEMAINE SUR DEUX (ET LA MOITIÉ DES VACANCES SCOLAIRES)",
        "UNE VIE DE CHAT",
        "VENTS DE SABLE, FEMMES DE ROC",
        "VICTOR",
        "VIE AU RANCH (LA)",
        "VIE SAUVAGE DES ANIMAUX DOMESTIQUES (LA)",
        "VILAIN (LE)",
        "VILLA AMALIA",
        "VINCERE",
        "VOYAGE AUX PYRENEES (LE)",
        "VOYAGE EN INDE (LE)",
        "WELCOME",
        "YONA LA LEGENDE DE L'OISEAU-SANS-AILE",
        "YUKI ET NINA",
    ];

    protected $categorie_data = [
        'Action ',
        'Animation ',
        'Aventure ',
        'Biographique ',
        'Catastrophe ',
        'Comédie ',
        'Comédie Dramatique ',
        'Comédie Musicale ',
        'Comédie Policière ',
        'Comédie Romantique ',
        'Court Métrage ',
        'Dessin Animé ',
        'Documentaire ',
        'Drame ',
        'Drame Psychologique ',
        'Epouvante ',
        'Erotique ',
        'Erotique X ',
        'Espionnage ',
        'Essai ',
        'Fantastique ',
        'Film à Sketches ',
        'Film Musical ',
        'Guerre ',
        'Historique ',
        'Horreur ',
        'Karaté ',
        'Manga ',
        'Mélodrame ',
        'Muet ',
        'Par Parties ',
        'Péplum ',
        'Policier ',
        'Politique ',
        'Programme ',
        'Romance ',
        'Science Fiction ',
        'Sérial ',
        'Spectacle ',
        'Téléfilm ',
        'Théâtre ',
        'Thriller ',
        'Western ',
    ];

    public function load(ObjectManager $manager)
    {
        /*
        // Creation des utilisateurs (User)
        $amountUser = 5;
        for ($i=0; $i < $amountUser ; $i++) { 
            $this->createUser($manager);
        }
        */
        
        // Creation des Catégorie (Categorie) et des films (Film)
        //$amountCategory = 50;
        $amountCategory = 10;
        $amountFilm= 100; // => 230 films in total
        for ($i=0; $i < $amountCategory ; $i++) { 
            $this->createCategorieAndFilm($manager, $amountFilm);
        }
    }

    public function createUser(ObjectManager $manager){
        $test_password = 'testglenn123*';
        $faker = Faker\Factory::create('fr_FR');
        $factory = $this->container->get('security.encoder_factory');
        $user_manager = $this->container->get('fos_user.user_manager');
        
        $email_domain = [
            '@gmail.com',
            '@wiley.com',
            '@yahoo.fr',
            '@contact.com',
            '@agency.net',
            '@crossknowledge.com',
            '@orange.com',
            '@edf.fr',
            '@nokia.com',
            '@airfrance.fr',
            '@skyline.com'
        ];
        
        $role_user = [
            'ROLE_USER',
            'ROLE_ADMIN',
        ];

        $enable_user = [
            true,
            false,
        ];

        $firstname = $faker->firstName;
        $lastname = $faker->lastName;
        $userPersonInfo = str_replace(" ", "", trim($firstname.'.'.$lastname));
        $username = strtolower($this->normalizeCharacters($userPersonInfo));
        $email = $username . $email_domain[array_rand($email_domain)];
        $role = $role_user[array_rand($role_user)];

        $user = $user_manager->createUser();
        $user->setFirstname($firstname);
        $user->setLastname($lastname);
        $user->setUsername($username);
        $user->setEmail($email);
        $user->setRoles(array($role));
        $user->setEnabled(true);
        $encoder = $factory->getEncoder($user);
        $password = $encoder->encodePassword($test_password, $user->getSalt());
        $user->setPassword($password);
        $user_manager->updateUser($user);
        unset($user);
    }

    public function createCategorieAndFilm(ObjectManager $manager, $amountFilm){

        // Récupération des utilisateurs (owner) de test.
        $user_manager = $this->container->get('fos_user.user_manager');
        $playground = $user_manager->findUserByUsername('playground');
        $videotheque = $user_manager->findUserByUsername('videotheque');
        $userRack = [
            $playground,
            $videotheque,
        ];
        $userSelected = array_rand($userRack);

        // Creation des catégories (Categorie).
        $categorie = new Categorie($userRack[$userSelected]);
        $categorie->setNom($this->categorie_data[array_rand($this->categorie_data)]);
        $manager->persist($categorie);
        $manager->flush();

        $faker = Faker\Factory::create('fr_FR');
        for ($i=0; $i < $amountFilm; $i++) { 
            $film = new Film($userRack[$userSelected]);
            $film->setCategorie($categorie);
            $film->setTitre($this->film_data[array_rand($this->film_data)]);
            $film->setDateSortie($faker->dateTimeBetween($startDate = '-30 years', $endDate = 'now', $timezone = null)); //'yyyy-MM-dd'
            $film->setDescription($faker->realText($faker->numberBetween(20,100)));
            $manager->persist($film);
            $manager->flush();
        }
    }

    function normalizeCharacters(String $subject) {
        $char_map = array(
            "ъ" => "-", "ь" => "-", "Ъ" => "-", "Ь" => "-",
            "А" => "A", "Ă" => "A", "Ǎ" => "A", "Ą" => "A", "À" => "A", "Ã" => "A", "Á" => "A", "Æ" => "A", "Â" => "A", "Å" => "A", "Ǻ" => "A", "Ā" => "A", "א" => "A",
            "Б" => "B", "ב" => "B", "Þ" => "B",
            "Ĉ" => "C", "Ć" => "C", "Ç" => "C", "Ц" => "C", "צ" => "C", "Ċ" => "C", "Č" => "C", "©" => "C", "ץ" => "C",
            "Д" => "D", "Ď" => "D", "Đ" => "D", "ד" => "D", "Ð" => "D",
            "È" => "E", "Ę" => "E", "É" => "E", "Ë" => "E", "Ê" => "E", "Е" => "E", "Ē" => "E", "Ė" => "E", "Ě" => "E", "Ĕ" => "E", "Є" => "E", "Ə" => "E", "ע" => "E",
            "Ф" => "F", "Ƒ" => "F",
            "Ğ" => "G", "Ġ" => "G", "Ģ" => "G", "Ĝ" => "G", "Г" => "G", "ג" => "G", "Ґ" => "G",
            "ח" => "H", "Ħ" => "H", "Х" => "H", "Ĥ" => "H", "ה" => "H",
            "I" => "I", "Ï" => "I", "Î" => "I", "Í" => "I", "Ì" => "I", "Į" => "I", "Ĭ" => "I", "I" => "I", "И" => "I", "Ĩ" => "I", "Ǐ" => "I", "י" => "I", "Ї" => "I", "Ī" => "I", "І" => "I",
            "Й" => "J", "Ĵ" => "J",
            "ĸ" => "K", "כ" => "K", "Ķ" => "K", "К" => "K", "ך" => "K",
            "Ł" => "L", "Ŀ" => "L", "Л" => "L", "Ļ" => "L", "Ĺ" => "L", "Ľ" => "L", "ל" => "L",
            "מ" => "M", "М" => "M", "ם" => "M",
            "Ñ" => "N", "Ń" => "N", "Н" => "N", "Ņ" => "N", "ן" => "N", "Ŋ" => "N", "נ" => "N", "ŉ" => "N", "Ň" => "N",
            "Ø" => "O", "Ó" => "O", "Ò" => "O", "Ô" => "O", "Õ" => "O", "О" => "O", "Ő" => "O", "Ŏ" => "O", "Ō" => "O", "Ǿ" => "O", "Ǒ" => "O", "Ơ" => "O",
            "פ" => "P", "ף" => "P", "П" => "P",
            "ק" => "Q",
            "Ŕ" => "R", "Ř" => "R", "Ŗ" => "R", "ר" => "R", "Р" => "R", "®" => "R",
            "Ş" => "S", "Ś" => "S", "Ș" => "S", "Š" => "S", "С" => "S", "Ŝ" => "S", "ס" => "S",
            "Т" => "T", "Ț" => "T", "ט" => "T", "Ŧ" => "T", "ת" => "T", "Ť" => "T", "Ţ" => "T",
            "Ù" => "U", "Û" => "U", "Ú" => "U", "Ū" => "U", "У" => "U", "Ũ" => "U", "Ư" => "U", "Ǔ" => "U", "Ų" => "U", "Ŭ" => "U", "Ů" => "U", "Ű" => "U", "Ǖ" => "U", "Ǜ" => "U", "Ǚ" => "U", "Ǘ" => "U",
            "В" => "V", "ו" => "V",
            "Ý" => "Y", "Ы" => "Y", "Ŷ" => "Y", "Ÿ" => "Y",
            "Ź" => "Z", "Ž" => "Z", "Ż" => "Z", "З" => "Z", "ז" => "Z", "S" => "Z",
            "а" => "a", "ă" => "a", "ǎ" => "a", "ą" => "a", "à" => "a", "ã" => "a", "á" => "a", "æ" => "a", "â" => "a", "å" => "a", "ǻ" => "a", "ā" => "a", "א" => "a",
            "б" => "b", "ב" => "b", "þ" => "b",
            "ĉ" => "c", "ć" => "c", "ç" => "c", "ц" => "c", "צ" => "c", "ċ" => "c", "č" => "c", "©" => "c", "ץ" => "c",
            "Ч" => "ch", "ч" => "ch",
            "д" => "d", "ď" => "d", "đ" => "d", "ד" => "d", "ð" => "d",
            "è" => "e", "ę" => "e", "é" => "e", "ë" => "e", "ê" => "e", "е" => "e", "ē" => "e", "ė" => "e", "ě" => "e", "ĕ" => "e", "є" => "e", "ə" => "e", "ע" => "e",
            "ф" => "f", "ƒ" => "f",
            "ğ" => "g", "ġ" => "g", "ģ" => "g", "ĝ" => "g", "г" => "g", "ג" => "g", "ґ" => "g",
            "ח" => "h", "ħ" => "h", "х" => "h", "ĥ" => "h", "ה" => "h",
            "i" => "i", "ï" => "i", "î" => "i", "í" => "i", "ì" => "i", "į" => "i", "ĭ" => "i", "ı" => "i", "и" => "i", "ĩ" => "i", "ǐ" => "i", "י" => "i", "ї" => "i", "ī" => "i", "і" => "i",
            "й" => "j", "Й" => "j", "Ĵ" => "j", "ĵ" => "j",
            "ĸ" => "k", "כ" => "k", "ķ" => "k", "к" => "k", "ך" => "k",
            "ł" => "l", "ŀ" => "l", "л" => "l", "ļ" => "l", "ĺ" => "l", "ľ" => "l", "ל" => "l",
            "מ" => "m", "м" => "m", "ם" => "m",
            "ñ" => "n", "ń" => "n", "н" => "n", "ņ" => "n", "ן" => "n", "ŋ" => "n", "נ" => "n", "ŉ" => "n", "ň" => "n",
            "ø" => "o", "ó" => "o", "ò" => "o", "ô" => "o", "õ" => "o", "о" => "o", "ő" => "o", "ŏ" => "o", "ō" => "o", "ǿ" => "o", "ǒ" => "o", "ơ" => "o",
            "פ" => "p", "ף" => "p", "п" => "p",
            "ק" => "q",
            "ŕ" => "r", "ř" => "r", "ŗ" => "r", "ר" => "r", "р" => "r", "®" => "r",
            "ş" => "s", "ś" => "s", "ș" => "s", "š" => "s", "с" => "s", "ŝ" => "s", "ס" => "s",
            "т" => "t", "ț" => "t", "ט" => "t", "ŧ" => "t", "ת" => "t", "ť" => "t", "ţ" => "t",
            "ù" => "u", "û" => "u", "ú" => "u", "ū" => "u", "у" => "u", "ũ" => "u", "ư" => "u", "ǔ" => "u", "ų" => "u", "ŭ" => "u", "ů" => "u", "ű" => "u", "ǖ" => "u", "ǜ" => "u", "ǚ" => "u", "ǘ" => "u",
            "в" => "v", "ו" => "v",
            "ý" => "y", "ы" => "y", "ŷ" => "y", "ÿ" => "y",
            "ź" => "z", "ž" => "z", "ż" => "z", "з" => "z", "ז" => "z", "ſ" => "z",
            "™" => "tm",
            "@" => "at",
            "Ä" => "ae", "Ǽ" => "ae", "ä" => "ae", "æ" => "ae", "ǽ" => "ae",
            "ĳ" => "ij", "Ĳ" => "ij",
            "я" => "ja", "Я" => "ja",
            "Э" => "je", "э" => "je",
            "ё" => "jo", "Ё" => "jo",
            "ю" => "ju", "Ю" => "ju",
            "œ" => "oe", "Œ" => "oe", "ö" => "oe", "Ö" => "oe",
            "щ" => "sch", "Щ" => "sch",
            "ш" => "sh", "Ш" => "sh",
            "ß" => "ss",
            "Ü" => "ue",
            "Ж" => "zh", "ж" => "zh",
        );
        return strtr($subject, $char_map);
    }

    public function getOrder()
    {
        return 1;
    }
    
}

